#!/usr/bin/env zsh

DOTFILES_ROOT=~/.dotfiles
DOTFILES_REPO="https://github.com/pkruithof/dotfiles"

if ! type -f git > /dev/null 2>&1; then
  printf "\n[ \033[00;34m..\033[0m ] Install git first\n"
  exit
fi

if [[ ! -d ${DOTFILES_ROOT} ]]; then
  printf "\n[ \033[00;34m..\033[0m ] Downloading dotfiles to ${DOTFILES_ROOT}\n"
  git clone --recursive ${DOTFILES_REPO} ${DOTFILES_ROOT}
fi

${DOTFILES_ROOT}/bin/dotfiles
