#!/usr/bin/env bash

set -e

cd "$(dirname "${BASH_SOURCE}")"

source ${DOTFILES_ROOT}/environment
source ${DOTFILES_ROOT}/lib/output
source ${DOTFILES_ROOT}/lib/input
source ${DOTFILES_ROOT}/lib/tests
source ${DOTFILES_ROOT}/lib/utils
source ${DOTFILES_ROOT}/macos/lib/brew
source ${DOTFILES_ROOT}/macos/lib/phpbrew

brew_ensure
brew_update

phpbrew_ensure
phpbrew_update

# install system default settings
./bin/defaults
