#!/usr/bin/env zsh

##
## cd
##

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"


##
## ls
##
alias ls="ls --color" # colorize output
alias l="ls -Flh" # Long form
alias ll="l"
alias la="ls -Flah" # List all files
alias lsd='ls -Flh | grep "^d"' # List only directories
alias las="ls -FlahS" # Order by file size, long form, all files


##
## Docker, Kubernetes, etc.
##

alias pstorm="open -na \"PhpStorm.app\" --args"
alias k="kubectl"
alias kl="kubectl logs -f"
alias kp="kubectl get pods"
alias dc="docker compose"
alias dcl="dc logs -f"
alias dcps="dc ps --format \"table {{.ID}}\t{{.Service}}\t{{.State}}\t{{.Status}}\t{{.RunningFor}}\t{{.Image}}\""
alias cs="make cs-fix"
alias stan="make phpstan"
alias gh="github"
alias ci="cs && stan"
alias p="dc run --rm php sh"
alias t="dc run --rm test sh"
alias tf="dc run --rm test bin/phpunit --filter"


##
## various
##

alias afk="open -a /System/Library/CoreServices/ScreenSaverEngine.app"
alias grep="ggrep"

# quick hack to make watch work with aliases
alias watch='watch '

# IP addresses
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'

# Get public key, and optionally copy it to clipboard
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to clipboard.'"
