#!/usr/bin/env zsh

uuid () {
  echo "import uuid\nimport sys\nsys.stdout.write(str(uuid.uuid4()))" | python | pbcopy && echo -e 'generated uuid to clipboard'
}

passgen () {
  cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c ${1:-32}
}

docker-ips() {
  docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} - {{.Name}}' $(docker ps -aq) | sort
}

docker-ip() {
  docker inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$@"
}

setup-gcloud() {
  curl -o cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.darwin.amd64
  chmod +x cloud_sql_proxy
  sudo mv cloud_sql_proxy /usr/local/bin
  gcloud auth login
  gcloud auth configure-docker
  gcloud container clusters list
  echo "for each cluster run: gcloud container clusters get-credentials <name> --region <region>"
}
