#!/usr/bin/env zsh

# enable unlimited history
HISTFILE=${HOME}/.zsh_history
HISTSIZE=999999999
SAVEHIST=${HISTSIZE}

setopt append_history
setopt extended_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history
