#!/usr/bin/env zsh

# cd without using cd
setopt auto_cd

# show completion menu on successive tab press
setopt auto_menu
setopt complete_in_word
setopt always_to_end

# autocorrect
setopt correct
setopt correct_all

# history options
setopt append_history
setopt extended_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt share_history

