#!/usr/bin/env zsh

# cd without using cd
setopt auto_cd

# show completion menu on successive tab press
setopt auto_menu
setopt complete_in_word
setopt always_to_end

# autocorrect commands. don't use correctall here because
# it becomes too eager and annoying in suggestion corrections.
setopt correct

# history options
setopt append_history
setopt extended_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt share_history

