#!/usr/bin/env zsh

#
# Paths
#
typeset -gU fpath manpath path

# Set the list of directories that Zsh searches for programs.
path=(
  "${BREWPATH}/opt/coreutils/libexec/gnubin"
  "${BREWPATH}/opt/findutils/libexec/gnubin"
  $path
  "${HOME}/bin"
  /Applications/PhpStorm.app/Contents/MacOS
)

manpath=(
  "${BREWPATH}/opt/coreutils/libexec/gnuman"
  "${BREWPATH}/opt/findutils/libexec/gnuman"
  "${BREWPATH}/opt/grep/libexec/gnuman"
  "${BREWPATH}/share/man"
  /usr/share/man
  $manpath
)

fpath=(
  "${HOME}/.zsh"
  $fpath
)

eval "$(${BREWPATH}/bin/brew shellenv)"
