#!/usr/bin/env zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# use .localrc for settings specific to one system
[[ -f "$HOME/.localrc" ]] && source "$HOME/.localrc"

source "$HOME/.zsh/options"
source "$HOME/.zsh/paths"
source "$HOME/.zsh/aliases"
source "$HOME/.zsh/completion"
source "$HOME/.zsh/functions"
source "$HOME/.zsh/history"
source "$HOME/.zsh/input"
source "$HOME/.zsh/plugins"
source "$HOME/.zsh/gcloud"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"
